### ISSUE TITLE
still dumping old certificates

### ISSUE THREAD

**Issue by sakearzoo** [kereis/traefik-certs-dumper#130] opened 2023-01-10 16:36 UTC
```
version: '3.5'

services:
  certdumper:
    image: humenius/traefik-certs-dumper:edge-arm64v8
    volumes:
    - /home/traefik/acme.json:/traefik/acme.json:ro
    - /home/adguard/data/certs:/output:rw
    - /home/anonaddy/data/certs:/output1:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/anonaddy/data/hook.sh:/hook/hook.sh:ro
    environment:
    - CERTIFICATE_FILE_NAME=fullchain
    - PRIVATE_KEY_FILE_NAME=privkey
    - OVERRIDE_UID=1000
    - OVERRIDE_GID=1000
    
    network_mode: "none" 
```

after traefik renews the certificate from letsencrypt . the docker container still dumping old certs. i have seen that acme.json still contains old certs and also the new certs for my domain. but the docker dumping old certs not the latest certs . is there any way to fix this?

**Comment by kereis** [comment] 2023-01-10 19:52
Hi,

I think this is caused by the way Docker handles file mounts. Could you try to mount the directory containing the `acme.json` instead?

**Comment by kereis** [comment] 2023-01-24 16:20
Are the newer certificates also available inside the container, if you `cat` into mounted `acme.json`?

**Comment by kereis** [comment] 2023-01-29 13:55
Based on that example, I'd guess that `cloudflare`, `production` and `staging` are certresolvers in Traefik.
I'm wondering if this is more related to the behaviour of traefik-certs-dumper. However, I'm currently not sure how traefik-certs-dumper handles multiple certresolvers when dumping them, especially if there are two certificates of the same domain, but in different certresolvers.

Your solution might sound good, but if we have to fix that on our end, then it would require reading and a copy or modification of the input `acme.json`, as we have to remove the n-th certificate in all the other certresolvers; if that's okay.

**Comment by kereis** [comment] 2023-03-04 11:54
Hey @sakearzoo,

were you able to solve your issue? Or should we investigate this further by opening an issue over at https://github.com/ldez/traefik-certs-dumper/?

**Comment by sakearzoo** [comment] 2023-03-04 12:18
> Hey @sakearzoo,
> 
> were you able to solve your issue? Or should we investigate this further by opening an issue over at https://github.com/ldez/traefik-certs-dumper/?

I was unable to resolve yet .. currently i am using cron shell script to do this .

**Comment by kereis** [comment] 2023-03-04 12:19
Do you use the cron job with a traefik-certs-dumper binary or is it completely self-made?

**Comment by kereis** [comment] 2024-01-04 23:51
Hi @sakearzoo, as there have been no new updates, I will close this issue. You can re-open it if you need to. :)

**Closed by kereis** 2024-01-04 23:51 UTC
Labels: type: bug
